  name: Firecracker
  main: xenialdan\Firecracker\Loader
  version: 1.0.0
  api: ["3.11"]
  load: POSTWORLD
  authors: [XenialDan]
  prefix: "Firecracker"
  commands:
   firecracker:
    description: "Commands for Firecracker"
    usage: "/firecracker get"
    permission: firecracker.command
    aliases: [fc]
  permissions:
    firecracker.command:
      description: Permission for /firecracker commands.
      default: true
